export const CONSTANTS = {
  ZERO: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  SEVEN: 7,
  TEN: 10,
  ELEVEN: 11,
  THIRTEEN: 13,
  THIRTY_TWO: 32,
  FIFTY: 50,
  ONE_EIGHTY: 180,

  INTERVAL_2400: 2400,
  SPACE_CODE: 32,
  START_DATE: 'Start date',
  END_DATE: 'End date',
  CLEAR: 'Clear',
  APPLY: 'Apply',
  SAVE: 'Save',
  FULL_MONTH: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  SHORT_MONTH: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

  CMA_DISABLED: 'cma-disabled',
  CMA_NEXT_DISABLED: 'cma-nex-disabled',
  CMA_PREV_DISABLED: 'cma-prev-disabled',
};
